#!/usr/bin/env python
from JAK.Application import JWebApp


def office():
    # v2.0.3
    start = "https://www.wikipedia.org/"
    icon = "/usr/share/wikiaccess/wiki.png"

    adverts = "tpc.googlesyndication.com", "googleads.g.doubleclick.net", "tag.sp.advertising.com",\
              "banner.advertising.com", "cdn.bannerflow.com", "acdn.adnxs.com"

    rules = {"block": adverts}

    toolbar = {"name": "Wikipedia", "url": "https://www.wikipedia.org"},\
              {"name": "WikiMedia", "url": "https://commons.wikimedia.org/wiki/Main_Page"},\
              {"name": "Wiktionary", "url": "https://www.wiktionary.org"},\
              {"name": "WikiData", "url": "https://www.wikidata.org/wiki/Wikidata:Main_Page"},\
              {"name": "WikiNews", "url": "https://www.wikinews.org"},\
              {"name": "WikiBooks", "url": "https://www.wikibooks.org"},\
              {"name": "WikiVersity", "url": "https://www.wikiversity.org"},\
              {"name": "WikiQuote", "url": "https://www.wikiquote.org"},\
              {"name": "MediaWiki", "url": "https://www.mediawiki.org/wiki/MediaWiki"},\
              {"name": "WikiSource", "url": "https://wikisource.org/wiki/Main_Page"},\
              {"name": "WikiSpecies", "url": "https://species.wikimedia.org/wiki/Main_Page"},\
              {"name": "WikiVoyage", "url": "https://www.wikivoyage.org"},\
              {"name": "MetaWiki", "url": "https://meta.wikimedia.org/wiki/Main_Page"},\

    webapp = JWebApp(title="WikiAccess", icon=icon, web_contents=start, online=True, toolbar=toolbar)

    return webapp


office().run()
